apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: niaphilanthropy-www-mvc-deployment
spec:
  replicas: 1
  minReadySeconds: 10 
  strategy:
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: niaphilanthropy-www-mvc
    spec:
      containers:
      - name: niaphilanthropy-www-mvc
        image: soonieacr.azurecr.io/niaphilanthropy-www-mvc:v1
        ports:
        - containerPort: 80
        imagePullPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: niaphilanthropy-www-mvc-service
spec:
  type: ClusterIP
  ports:
  - name:
    port: 80
  selector:
    app: niaphilanthropy-www-mvc